# Generated by Django 5.0.6 on 2024-06-02 10:25

import django.db.models.deletion
import webapp.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=20, verbose_name='Title')),
                ('category', models.CharField(choices=[('1', 'Good'), ('2', 'Service')], max_length=30, verbose_name='Category')),
                ('description', models.TextField(max_length=500, verbose_name='Description')),
                ('img', models.ImageField(upload_to='publications_images', verbose_name='Avatar')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated at')),
                ('text', models.TextField(max_length=400, verbose_name='Comment')),
                ('grade', webapp.models.IntegerRangeField(verbose_name='Grade')),
                ('status', models.CharField(choices=[('1', 'Moderate'), ('2', 'Approve'), ('3', 'Rejection')], default=1, max_length=30, verbose_name='Status')),
                ('author', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='reviews', to=settings.AUTH_USER_MODEL, verbose_name='Author')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='webapp.product', verbose_name='Product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
