# Generated by Django 5.0.6 on 2024-06-04 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_product_avg_grade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avg_grade',
            field=models.FloatField(default=0, verbose_name='Avg grade'),
        ),
    ]
